# -*- coding: utf-8 -*-
"""Edubridge_NLP_Sentimental_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xk6fOvsZf1bNkDuKe26qH6T_s5lBZoHh

**Sentimental Alalysis**

using NLP
"""

# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Load dataset

df = pd.read_csv("sentiment_dataset.csv")

# Display first 5 rows
print(df.head())

# Input and output
X = df['review']
y = df['sentiment']

# Convert text into numerical values using TF-IDF
vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(X)

# Split data properly
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
print()
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print()

# Classification report
print(classification_report(y_test, y_pred, zero_division=0))

# Test custom review
custom_review = ["The movie was fantastic and emotional"]

# Transform review
custom_vector = vectorizer.transform(custom_review)

# Predict sentiment
prediction = model.predict(custom_vector)

print("\nCustom Review Prediction:")
print(prediction[0])

