# -*- coding: utf-8 -*-
"""Edubridge_NLP_Resume_Screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E14-FpKpEbb3QDWfYJbJ2nwFGhKptyPW

**Resume Screening**

using NLP
"""

# Import libraries
import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Download stopwords
nltk.download('stopwords')

# Load dataset
df = pd.read_csv("/content/resume_screening_dataset.csv")

# Display dataset
print(df.head())

# Initialize tools
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

# Preprocessing function
def preprocess_text(text):

    # Lowercase
    text = text.lower()

    # Remove punctuation/numbers
    text = re.sub(r'[^a-zA-Z]', ' ', text)

    # Tokenization
    words = text.split()

    # Remove stopwords and stemming
    words = [
        ps.stem(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

# Apply preprocessing
df['clean_resume'] = df['resume_text'].apply(preprocess_text)

# Features and labels
X = df['clean_resume']
y = df['job_role']

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(max_features=5000)

X_vectorized = vectorizer.fit_transform(X)

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Model
model = LogisticRegression(max_iter=1000)

# Train
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

# Classification Report
print("\nClassification Report:\n")

print(classification_report(y_test, y_pred))

# Custom Resume Prediction
custom_resume = [

    '''
    Skilled in Python, Machine Learning, Deep Learning,
    NLP, TensorFlow, SQL, Pandas and Scikit-learn.
    Worked on AI and analytics projects.
    '''
]

# Preprocess
custom_clean = [preprocess_text(text) for text in custom_resume]

# Vectorize
custom_vector = vectorizer.transform(custom_clean)

# Predict
prediction = model.predict(custom_vector)

print("\nPredicted Role:", prediction[0])